config/routes.rb
ComunidadBox::Application.routes.draw do

  match 'auth/:provider/callback' => 'authentications#create'
  match "admin" => "admin#show"
  match "conf" => "conf#show"
  match "vgneumaticos"=>"guests#new"

  constraints CanAccessResque do
    mount Resque::Server, at: '/resque'
  end

  scope '(:locale)' do
    devise_for :users,:controllers => { :registrations => "users/registrations",:sessions =>'users/sessions',:confirmations =>"users/confirmations" }
    match "/help" => "help#index"

    resources :company_attributes
    resources :item_service_requests
    resources :service_requests
    resources :guests
    resources :authentications
    resources :service_filters
    resources :states
    resources :countries
    resources :brands
    resources :models do
      collection do
        post :import
      end
    end

    resources :notes
    resources :item_services
    resources :car_filters
    resources :ranks
    resources :tasks
    resources :payment_methods
    resources :service_type_templates
    resources :contacts
    resources :material_requests
    resources :advertising
    resources :statuses

    resources :messages do
      member do
        get :email
        post :read
      end

      collection do
        get :users
      end
    end

    resources :home do
      collection do
        post :set_company
      end
    end

    resources :messages do
      member do
        post :respond
      end
    end

    resources :events do
      resources :notes
      resources :alarms

      member do
        get :search_notes
      end
    end

    resources :budgets do
      resources :notes
      collection do
        get :export
      end
      member do
        get :print
        get :email
        get :email_s
        put :undelete
      end
    end

    resources :employees do
      collection do
        post :search
      end

      member do
        get :activate
      end

    end

    resources :workorders do
      collection do
        get :filter
        post :task_list
        get :autopart
        get :export
      end
      member do
        get :notify
        get :print
        get :price_offer
        post :save_price_offer
        get :price_offers
        put :confirm_price_offer
        put :undelete
      end
    end

   resources :companies do
      collection do
        get :service_types
        get :all
        get :admin
        post :search
        post :search_distance
        post :add_service_type
        post :remove_service_type
      end

      member do
        get :activate
      end
    end

    resources :vehicles do
      resources :alarms
      resources :notes

      collection do
        get :find_models
        get :find_brands
        post :find_company_models_by_brand
        post :search
        post :search_companies
        get :my
      end

      member do
        put :km
        get :services_done
        get :future_events
        get :report_graph
        get :notes
        get :alarms
        get :messages
      end
    end

    resources :users do
      resources :messages

      collection do
        get :generate_email
        get :validate_email
        get :validate_domain
        get :new_employee
        get :list_service_offer
        get :companies
        get :future_events
        post :find_models
        get :mail_confirmation
        get :reset_password
        get :unlock
      end

    end

    resources :alarms do
      collection do
        get :list_alarm_now
      end
      member do
        get :send_alarm
      end
    end

    resources :clients do
      collection do
        get :search
        get :index_all
        get :export
        get :import
        put :upload
      end
    end

    resources :services do
      collection do
        post :add_material
        post :add_service
      end
    end

    resources :control_panels do
      collection do
        post :filter_alarms
        get :filter_alarms
        post :find_models
        post :save_filter
      end
    end

    resources :service_offers do
      collection do
        post :send_notification
        post :new_s
        get :notify_email
        get :notify
      end
      member do
        get :show_ad
      end

    end

    resources :vehicle_service_offers do
      member do
        get :confirm
        get :reject
      end
      collection do
        get :confirmed
      end
    end

    resources :service_types do
      resources :materials do
        member do
          delete :remove
        end
      end

      member do
        get :task_list
        put :add_task
        delete :remove_task
        post :add_material
        post :protect
        post :unprotect
        get :search_material
      end

      collection do
        get :search_sub_category
        put :destroy_material
      end
    end

    resources :materials do

      resources :service_types do
        member do
          delete :remove
        end
      end
      collection do
        get :details
        get :export
        post :import
      end
    end

    resources :price_lists do
      member do
        get :activate
        get :items
        get :copy
        put :update_item_price
        put :price_upload
        get :export
      end

      collection do
        get :import_price
      end
    end

    resources :material_requests do
      collection do
        post :search
      end
      member do
        get :approved
        get :disapproved
      end
    end

    resources :exports do
      member do
        get :download
        get :run
      end
    end

    resources :company_material_codes do
      collection do
        get :export
        post :import
      end
    end

    root :to => "home#index"

  end

end

app/models/note.rb
# encoding: utf-8
class Note < ActiveRecord::Base
	attr_accessible :message, :budget_id, :workorder_id, :event_id,:note_id,:vehicle_id,:creator_id,:receiver_id,:respond_to,:user_id

	belongs_to :user
	belongs_to :company
	belongs_to :vehicle
	belongs_to :workorder
	belongs_to :event
	belongs_to :budget
	belongs_to :note
	belongs_to :alarm
	belongs_to :creator,:class_name =>"User",:foreign_key=>'creator_id'
  belongs_to :receiver,:class_name =>"User",:foreign_key=>'receiver_id'
  belongs_to :respond_to,:class_name =>"Note",:foreign_key=>'respond_to_id'

  validates :message,:presence => true
 	before_save :set_company_id

 	def set_company_id
 		self.company_id = self.creator.company_id if creator.company_id
 	end

	def self.for_user(user)
		where("user_id = ?",user.id).order("created_at desc")
	end

	def self.for_event_end_user(event,user)
    Note.where("event_id = ? && company_id IN (?)",event.id,user.get_companies_ids)
  end

end

app/controllers/notes_controller.rb
# encoding: utf-8
class NotesController < ApplicationController
  layout "application", :except => [:create,:destroy]
  # GET /notes
  # GET /notes.xml
  def index
    page = params[:page] || 1
    per_page = 10
    @notes = current_user.all_notes.paginate(:page =>page,:per_page =>per_page)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.xml
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.xml
  def new
    @note = Note.new
    t = params[:t] || :b
    respond_to do |format|
      #format.html # new.html.erb
      format.html
      format.xml  { render :xml => @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.xml
  def create

    if params[:event_id]
      event = Event.find(params[:event_id])
      @note = event.notes.build(params[:note])
      @note.user = event.vehicle.user
    else
      @note = Note.new(params[:note])
    end

    set_note_element_id
    @id = params[:element_id]

    @note.creator = current_user

    respond_to do |format|
      if @note.save
        format.js {render :file=>"notes/new_note",:layout => false}
      else
        format.js {render :file=>"notes/error",:layout => false}
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.xml
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to(notes_path) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  def set_note_element_id
    @element_id = "#notes .notes_container"
    @element_id = "#budget_#{@note.budget_id}" if @note.budget_id
    @element_id = "#workorder_#{@note.workorder_id}" if @note.workorder_id
    @element_id = "#event_notes .notes_container" if @note.event_id
  end

  # DELETE /notes/1
  # DELETE /notes/1.xml
  def destroy
    @note = Note.find(params[:id])
    @note_id = @note.id
    @wo_id = @note.workorder_id

    set_note_element_id

    @note.destroy

    respond_to do |format|
      format.html { redirect_to(notes_url) }
      format.js {render :layout => false}
      format.xml  { head :ok }
    end
  end
end

app/views/notes/_all_notes_data.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.datetime_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :recall %><br />
    <%= f.datetime_select :recall %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :workorder_id %><br />
    <%= f.text_field :workorder_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :note_id %><br />
    <%= f.text_field :note_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/_form.haml
= form_for @note,:html=>{:class=>"nn"} do |f|
  .box_bottom
    - if @note.errors.any?
      #error_explanation
        %h2
          = pluralize(@note.errors.count, "error")
          prohibited this note from being saved:
        %ul
          - @note.errors.full_messages.each do |msg|
            %li= msg
    %table
      %tr
        %td{:style=>"width:100px"}
          Nota
        %td
          = f.text_area :message,:cols => 57, :rows => 3
  = f.submit "Grabar",:class=>"button"      
  .box_bottom    

app/views/notes/_new_menu.haml
%li
  #alarms_link.menu
    = image_tag "alarm.png",:class=> :left
    = link_to "Alarmas",alarms_path,:class=> :left
    #today_alarm
      = alarm_today_nro
%li
  #messages_link.menu        
    = image_tag "message.png",:class=> :left
    = link_to "Mensajes", messages_path,:class => :left
    #unread_message_nro
      = unread_message_nro current_user
%li
  #note.link.link.menu
    = image_tag "notes.png"
    = link_to "Notas",notes_path

app/views/notes/_note_form.haml
.new_note_form
  = form_for :note,:remote=>true,:url => notes_path,:html=>{:class=>:note_form} do |f|
    = f.text_area :message,:cols=>64,:rows=>2,:class =>:left,:title =>"",:placeholder =>t(".note")
    = hidden_field_tag :element_id,element_id
    - if defined? wo
      = f.hidden_field :workorder_id,:value => wo
    - if defined? b
      = f.hidden_field :budget_id,:value => b
    - if defined? c
      = f.hidden_field :vehicle_id,:value => c
    .left
      = image_submit_tag "ok.png",:title =>"Grabar"

app/views/notes/_note_form_np.haml
.notes_container.box_top{:id => "notes_container_#{id}"}
  .msg_errors.hide
  = render :partial => "notes/note_form",:locals=>{:wo => wo,:b=>b,:c => c,:element_id => id}
  .notes
    - notes.each do |note|
      = render :partial =>'notes/notes_small_view',:locals=>{:wo => wo,:b=>b,:note =>note}
  

app/views/notes/_note_form_p.haml
.notes_container.hide
  = render :partial => "notes/note_form",:locals=>{:wo => wo,:b=>b,:c => c,:element_id => element_id}
  .notes.hide
    - if notes && notes.size > 0
      = render :partial =>'notes/notes_small_view',:collection => notes,:as=>:note    
      .clear
        = will_paginate notes

app/views/notes/_notes_small_view.haml
-#%div{:id=>"note-#{note.id}",:class=>"note clear"}
%div[note]
  .info_note
    .left
      = note.message
    .right
      .date
        %lable{:title =>"Creado el"}
          = l note.created_at,:format => :short
      .user.right.clear
        %label{:title =>"Creado por"}
          =note.creator.full_name
  .notes_fk
    - if note.event
      = link_to "",event_path(note.event),:class=>"event_s",:title =>"Servicio a Realizar"
    - if note.workorder
      = link_to "",workorder_path(note.workorder),:class =>"service_s",:title =>"Servicio Realizado"
    - if note.budget
      = link_to "",budget_path(note.budget),:class=>"budget_s",:title =>"Presupuesto"
    - if note.vehicle
      =# link_to "",car_path(note.vehicle),:class=>"note_car",:title =>"Automovil"
      =# link_to "", sti_vehicle_path(note.vehicle.type, note.vehicle), :class => "note_car", :title => "Automovil"
      = link_to "", vehicle_path(note.vehicle), :class => "note_car", :title => "Automovil"
    - if note.alarm
      = link_to "",alarm_path(note.alarm),:class=>"has_alarms",:title =>"Alarma"

  -if note.creator_id == current_user.id
    .actions
      .action.hide
        = link_to "",edit_note_path(note),:class=>"edit",:title =>"Modificar"
      .action
        = link_to "", note_path(note),:method => :delete,:data =>{ :confirm => '¿ Esta seguro que desea borrar la Nota ?'},:title =>"Eliminar",:remote=> true,:class=>:delete

app/views/notes/basic_note.haml
<%= form_for(@note) do |f| %>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
<% end %>

app/views/notes/destroy.js.erb
$("#note_<%=@note_id%>").fadeOut().remove();

app/views/notes/error.js.erb
$("#notes_container_<%=@id%> .msg_errors").html("<%=escape_javascript(render(:partial =>'shared/error_messages',:locals =>{:target => @note}))%>").show();

app/views/notes/new.haml
.vertical_menu
  = render "home/menu"
  .menu_actions.box_bottom
    %ul
      %li
        = link_to "Nueva Nota",new_note_path
.contentright_s
  .box_bottom
    %h1=(".new_note")
  = render 'form'

app/views/notes/new_note.js.erb
$("<%=@element_id%>").find(".notes").show().prepend("<%=escape_javascript(render(:partial=>'notes_small_view',:locals=>{:note=>@note}))%>");
$("<%=@element_id%> .note").first().effect("highlight", {color:"#F7DE4F"}, 3000);

app/views/notes/notes_form.haml
.notes
  = form_for "note" do |f|         
    .left    
      = f.label(:message,"Nota",:class => :left)
      %br
      = f.text_area :message,:cols=>50,:rows=>3      
      = f.hidden_field :user_id
    .right.clear
      = f.submit "Grabar",:class=>:button

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @note.message %>
</p>

<p>
  <b>Due date:</b>
  <%= @note.due_date %>
</p>

<p>
  <b>Recal:</b>
  <%= @note.recall %>
</p>

<p>
  <b>Start date:</b>
  <%= @note.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @note.end_date %>
</p>

<p>
  <b>User:</b>
  <%= @note.user_id %>
</p>

<p>
  <b>Workorder:</b>
  <%= @note.workorder_id %>
</p>

<p>
  <b>Status:</b>
  <%= @note.status %>
</p>

<p>
  <b>Note:</b>
  <%= @note.note_id %>
</p>


<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>