config/routes.rb
ComunidadBox::Application.routes.draw do

  match 'auth/:provider/callback' => 'authentications#create'
  match "admin" => "admin#show"
  match "conf" => "conf#show"
  match "vgneumaticos"=>"guests#new"

  constraints CanAccessResque do
    mount Resque::Server, at: '/resque'
  end

  scope '(:locale)' do
    devise_for :users,:controllers => { :registrations => "users/registrations",:sessions =>'users/sessions',:confirmations =>"users/confirmations" }
    match "/help" => "help#index"

    resources :company_attributes
    resources :item_service_requests
    resources :service_requests
    resources :guests
    resources :authentications
    resources :service_filters
    resources :states
    resources :countries
    resources :brands
    resources :models do
      collection do
        post :import
      end
    end

    resources :notes
    resources :item_services
    resources :car_filters
    resources :ranks
    resources :tasks
    resources :payment_methods
    resources :service_type_templates
    resources :contacts
    resources :material_requests
    resources :advertising
    resources :statuses

    resources :messages do
      member do
        get :email
        post :read
      end

      collection do
        get :users
      end
    end

    resources :home do
      collection do
        post :set_company
      end
    end

    resources :messages do
      member do
        post :respond
      end
    end

    resources :events do
      resources :notes
      resources :alarms

      member do
        get :search_notes
      end
    end

    resources :budgets do
      resources :notes
      collection do
        get :export
      end
      member do
        get :print
        get :email
        get :email_s
        put :undelete
      end
    end

    resources :employees do
      collection do
        post :search
      end

      member do
        get :activate
      end

    end

    resources :workorders do
      collection do
        get :filter
        post :task_list
        get :autopart
        get :export
      end
      member do
        get :notify
        get :print
        get :price_offer
        post :save_price_offer
        get :price_offers
        put :confirm_price_offer
        put :undelete
      end
    end

   resources :companies do
      collection do
        get :service_types
        get :all
        get :admin
        post :search
        post :search_distance
        post :add_service_type
        post :remove_service_type
      end

      member do
        get :activate
      end
    end

    resources :vehicles do
      resources :alarms
      resources :notes

      collection do
        get :find_models
        get :find_brands
        post :find_company_models_by_brand
        post :search
        post :search_companies
        get :my
      end

      member do
        put :km
        get :services_done
        get :future_events
        get :report_graph
        get :notes
        get :alarms
        get :messages
      end
    end

    resources :users do
      resources :messages

      collection do
        get :generate_email
        get :validate_email
        get :validate_domain
        get :new_employee
        get :list_service_offer
        get :companies
        get :future_events
        post :find_models
        get :mail_confirmation
        get :reset_password
        get :unlock
      end

    end

    resources :alarms do
      collection do
        get :list_alarm_now
      end
      member do
        get :send_alarm
      end
    end

    resources :clients do
      collection do
        get :search
        get :index_all
        get :export
        get :import
        put :upload
      end
    end

    resources :services do
      collection do
        post :add_material
        post :add_service
      end
    end

    resources :control_panels do
      collection do
        post :filter_alarms
        get :filter_alarms
        post :find_models
        post :save_filter
      end
    end

    resources :service_offers do
      collection do
        post :send_notification
        post :new_s
        get :notify_email
        get :notify
      end
      member do
        get :show_ad
      end

    end

    resources :vehicle_service_offers do
      member do
        get :confirm
        get :reject
      end
      collection do
        get :confirmed
      end
    end

    resources :service_types do
      resources :materials do
        member do
          delete :remove
        end
      end

      member do
        get :task_list
        put :add_task
        delete :remove_task
        post :add_material
        post :protect
        post :unprotect
        get :search_material
      end

      collection do
        get :search_sub_category
        put :destroy_material
      end
    end

    resources :materials do

      resources :service_types do
        member do
          delete :remove
        end
      end
      collection do
        get :details
        get :export
        post :import
      end
    end

    resources :price_lists do
      member do
        get :activate
        get :items
        get :copy
        put :update_item_price
        put :price_upload
        get :export
      end

      collection do
        get :import_price
      end
    end

    resources :material_requests do
      collection do
        post :search
      end
      member do
        get :approved
        get :disapproved
      end
    end

    resources :exports do
      member do
        get :download
        get :run
      end
    end

    resources :company_material_codes do
      collection do
        get :export
        post :import
      end
    end

    root :to => "home#index"

  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :name, :description
  
  validates_presence_of :description

  has_and_belongs_to_many :service_types
end

app/controllers/price_lists_controller.rb
class PriceListsController < ApplicationController
  
  #authorize_resource

  def show
    @price_list = PriceList.find(params[:id])
    authorize! :read, @price_list
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @price_list }
    end
  end
  
  def import_price
    name = params[:name]
    PriceList.import_price name
    redirect_to :action=>:index
  end
  
  # GET /models/1/edit
  def edit
    @price_list = PriceList.find(params[:id])
  end
  
  # GET /models/new
  # GET /models/new.xml
  def new
    @price_list = PriceList.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @model }
    end
  end

  def destroy
    @pl = PriceList.find params[:id]
    @pl.destroy
    respond_to do |format|
      format.html { redirect_to(price_lists_path) }
    end
  end
  
  # POST /models
  # POST /models.xml
  def create
    @price_list = PriceList.new(params[:price_list])
    @price_list.active=0
    @price_list.company = get_company
    respond_to do |format|
      if @price_list.save
        flash[:notice] = 'La Lista de Precio de grabo con exito'
        format.html { redirect_to(price_lists_path) }
        format.xml  { render :xml => @price_list, :status => :created, :location => @price_list }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @price_list.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def index
    @price_lists = get_all_price_list(company_id)
  end
  
  def get_all_price_list(company_ids)
    PriceList.joins(:company).where("company_id IN (?)",company_ids).order("companies.name, name")
  end
  
  def copy
    @pl = PriceList.find params[:id]
    PriceList.copy_price_list @pl
    respond_to do |format|
      format.html { redirect_to(price_lists_path) }
    end
  end
  
  def activate
    pl = PriceList.find(params[:id])
    pl.activate    
    redirect_to :action=>:index
  end

   # PUT /models/1
  # PUT /models/1.xml
  def update
    @price_list = PriceList.find(params[:id])

    respond_to do |format|
      if @price_list.update_attributes(params[:price_list])
        format.html { redirect_to price_lists_path}
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @price_list.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def update_item_price
    plid= params[:id]
    ids = params[:ids]
    
    page = params[:page]
    item_update = params[:item_update]
    percentage = params[:percentage]
    service_types_ids = params[:service_type_ids]
    material = params[:material]
    
    update_all(plid,percentage) if (item_update == "all")      
    
    update_all_page(plid,percentage,service_types_ids,material)if (item_update == "all_page")
    
    update_actual_page(plid,ids) if (item_update == "actual_page")
    
    redirect_to :action=>:index
  end
  
  def items
    id = params[:id]
    @price_list = PriceList.find id
    authorize! :read, @price_list

    @page = params[:page] || 1
    @service_type_ids = params[:service_type_ids] ? params[:service_type_ids].values : []
    @percentage = params[:percentage] || ""
    @material = params[:material] || ""
    company_id= get_company.id
    @materials = MaterialServiceType.m(company_id,id,@service_type_ids,@material,@page.to_i)
    respond_to do |format|
      format.html
    end
  end
  
  def price_upload
    if params[:price][:file].present?
      price_list = PriceList.find params[:id]
      authorize! :import, price_list
      MaterialServiceType.import_to_update_price params[:id], params[:price][:file], current_user,get_user_agent_encode
    else
      flash[:alert] = t("Error")
    end

    redirect_to items_price_list_path

  end

#  def price_upload
#    require 'fileutils'
#    id = params[:id]
#    @price_list = PriceList.find id
#    tmp = params[:price][:file].tempfile
#    file_name = params[:price][:file].original_filename
#    @result = PriceList.import_item_price_file(@price_list,tmp,file_name)
#    #file = File.join("#{RAILS_ROOT}/files/", params[:price][:file].original_filename)
#    #FileUtils.cp tmp.path, file,"Bridgestone")
#    #redirect_to items_price_list_path(PriceList.find(id))    
#    @result[:file_name] =params[:price][:file].original_filename
#    @page = 1
#    @service_type_ids = []
#    @percentage = ""
#    @material =  ""
#    company_id= get_company.id
#    @materials = MaterialServiceType.m(company_id,id,@service_type_ids,@material,@page.to_i)
#      
#    respond_to do |format|
#      format.html { render :action => "items" }
#    end
#  end
  
  def export
    csv = MaterialServiceType.to_csv_for_update_price params[:id], current_user
    unless csv.empty?
      #encode = get_user_agent_encode
      respond_to do |format|        
        format.csv { send_data csv.encode("iso-8859-1"), 
                      :type => "text/csv; charset=iso-8859-1; header=present",
                      :disposition => "attachment; filename=priceList.csv"}
        format.html {redirect_to price_lists_path}
      end
      
    else
      flash[:alert] = t("Error")
      redirect_to price_lists_path
    end
  end

  private
  
  def get_materials
    id = params[:id]
    @page = params[:page] || 1
    @service_type_ids = params[:service_type_ids] || []
    @percentage = params[:percentage] || ""
    @material = params[:material] || ""
    company_id = get_company.id
    @materials = MaterialServiceType.m(company_id,id,@service_type_ids,@material,@page)
    @materials
  end
  
  def update_actual_page(plid,ids)
    PriceList.transaction do
        @price_list = PriceList.find plid
        ids.each_pair do |key,value|
          unless value.empty?
            mst=MaterialServiceType.find key.to_i
            items = PriceListItem.find_by_price_list_id_and_material_service_type_id(plid,key)
            if items
              items.price = value.to_f
              items.save
            else
              pli=PriceListItem.new        
              pli.material_service_type=mst
              pli.price = value.to_f
              @price_list.price_list_items << pli                     
            end          
          end
      end    
    end
  end
  
  def update_all_page(plid,percentage,service_types_ids,material)
    materials = MaterialServiceType.m(company_id,id,service_types_ids,material,-1)
    PriceList.transaction do
        materials.each do |key|
          mst=MaterialServiceType.find key.id
          items = PriceListItem.find_by_price_list_id_and_material_service_type_id(plid,key)
          items.price = items.price * (1 + (percentage.to_f / 100))
          items.save
      end    
    end
  end
  
  def update_all(plid,percentage)
    percentage = 1 + (percentage.to_f / 100)
    ActiveRecord::Base.connection.execute("update price_list_items set price = price * #{percentage} where price_list_id =#{plid}")
  end

end

app/views/price_lists/_file_upload.haml
.box_bottom
  %h1 
    = link_to "Actualizar desde archivo","#",:id =>"update_from_file"
.box_bottom.upload_file.hide
  .box_bottom
    .import_form
      %h4
        Por favor selecciones el archivo con los precios actualizados
      .box_bottom
        Antes de importar nuevos precios realize una 
        %strong
          exportación
        , y luego actualize los 
        %strong
          precios 
        usando una hoja de calculos
        .important
          Por favor solo modifique los valores de la columna precio, cualquier otro cambio realizado a las otras columnas sera ignorado por la importación      
        
      = form_for @price_list,:url => price_upload_price_list_path(@price_list),:html =>{:multipart => true} do |f|
        .left
          = file_field :price, :file
        .left
          = submit_tag "Importar",:disable_with => 'Importando...',:class =>:button
          = link_to "Exportar", export_price_list_path(@price_list,:format => :csv), :class => :button,:title => "Exportar Lista de precios"
  .box_bottom
    %h4
      Imagen ilustrativa de como debe ser el archivo para importar precios
    = image_tag("/images/import_price.png")    

app/views/price_lists/_form.haml
= render 'shared/error_messages', :target => @price_list  
= form_for(@price_list) do |f|
  .box_bottom
    %table.w
      %tr
        %td Nombre
        %td
          = f.text_field :name
  .box_bottom.buttons_container
    = f.submit "Grabar",:class=>"button"
    = link_to t("cancel"), price_lists_path

app/views/price_lists/_item.haml
%tr
  %td
    = item.name
  %td
    -unless item.material.prov_code.empty?
      = "[#{item.material.prov_code}]" 
    = item.material.name
  %td.currency.number    
    = number_to_currency item.price
  %td
    %input{:id=>"ids_#{item.id}",:name=>"ids[#{item.id}]",:value=>number_with_precision(item.price),:class=>"currency_input price"}
    %label.diff.right       

app/views/price_lists/_update.haml
#service_types.box_bottom
  %h3 Tipos de Servicios
  = form_for @price_list,:url => items_price_list_path(@price_list),:html=>{:method =>:get} do |ff|
    %table
      %tbody
      - for service_type in get_service_types
        %tr
          %td
            = check_box_tag "service_type_ids[#{service_type.id}]",service_type.id,@service_type_ids.include?(service_type.id.to_s),:class =>"service_type_id checkbox"
            = label_tag "service_type_ids[#{service_type.id}]",service_type.name,:class =>:link
      %tr
        %td
          = text_field_tag "material",@material,:class=>"labelify input",:title=>"Material"
      %tr
        %td
          = image_submit_tag("find.png",:class =>"input_img")

app/views/price_lists/edit.haml
.vertical_menu
  = render "admin/menu"
.contentright_s
  .box_bottom
    %h1 Modificar Lista de Precio
  = render "form"

app/views/price_lists/index.haml
.vertical_menu
  = render "admin/menu"
  .menu_actions.box_bottom
    %ul
      %li
        = link_to "Nueva Lista de Precio", new_price_list_path
.contentright_s
  -if company_id.size == 1
    .box_bottom
      %h1
        = get_company.name
  .box_bottom
    %h1
      Listas de Precios
  %table#sort_table.comboxtable
    %thead
      %tr
        -if company_id.size > 1
          %th Sucursal
        %th
          Nombre
        %th
          Estado
        %th
    - for price_list in @price_lists
      %tr
        -if company_id.size > 1
          %td
            = price_list.company.name
        %td
          = link_to h(price_list.name),items_price_list_path(price_list)
          - if price_list.company.nil?
            = link_to "Copiar",copy_price_list_path(price_list)
        %td
          = is_active(price_list,activate_price_list_path(price_list))
        %td
          = link_to '-Exp-', export_price_list_path(price_list,:format => :csv), :title => "Exportar Lista de precios"
          -unless price_list.company.nil?
            = link_to image_tag('edit.png'), edit_price_list_path(price_list),:title =>"Modificar"
          -if price_list.can_delete?(current_user)
            = link_to image_tag('delete.png'), price_list, :confirm => '¿ Esta seguro que desea borrarlo ?', :method => :delete,:title =>"Borrar"
          = link_to image_tag('new.png'), copy_price_list_path(price_list),:title =>"Copiar lista de precio"

app/views/price_lists/items.haml
-# javascript 'jquery.formatCurrency-1.4.0'
-# javascript 'jquery.formatCurrency.es-AR'
-# javascript 'price_list'
#price_list_items  
  .vertical_menu
    = render "admin/menu"
    = render "update"    
  .contentright_s
    .box_bottom
      %h1
        = @price_list.name
        \:
        = @price_list.company.name
    = render "file_upload.haml"
    - if @result
      #mpor_price_item
        .box_bottom
          %h1 Actalizar desde un archivo
        .box_bottom          
          %strong 
            Nombre archivo:
          = @result[:file_name] 
          %br
          %strong
            Precios actualizdos:
          = @result[:found]
          %br
          %strong
            Materiales no encontrados:
          = link_to " #{@result[:not_found]}","/price_files/#{@result[:not_found_material]}", target: "_blank",title: "Materiales no encontrados"
          %br

    .box_bottom
      %h1 
        = link_to "Listado de Precios","#",:id=>"price_list_items"
    #price_list_container
      = form_for @price_list,:url =>"update_item_price",:html =>{:id =>"price_list_form"} do |f|
        .box_bottom
          .import_form
            %table.w
              %tbody
                %tr
                  %td
                    %ol
                      %li
                        = radio_button_tag :item_update,:all,false,:class=>"checkbox"
                        = label_tag :item_update, "Todos los materiales",:for => :item_update_all,:class=>:link
                      %li
                        = radio_button_tag :item_update, :all_page,false,:class=>"checkbox"
                        = label_tag :item_update, "Todas las paginas",:for => :item_update_all_page,:class=>:link
                      %li
                        = radio_button_tag :item_update, :actual_page,true,:class=>"checkbox"
                        = label_tag :item_update, "Pagina actual",:for=>:item_update_actual_page,:class=>:link
                  %td
                    Incremento
                    = text_field_tag :percentage,@percentage
                    = link_to_function "Grabar","savePriceList()",:class =>"button"      
                    #service_types_ids{:style =>"display:none"}
                      = hidden_field_tag "material",@material
                      = hidden_field_tag "page",@page
          
        %table#sort_table.comboxtable
          %thead
            %tr.table_header
              %th{:width=>"25%"}
                Tipo de Servicio
              %th{:width=>"45%"}
                Material
              %th{:width=>"10%"}
                Precio
              %th{:width=>"20%"}
                Nuevo Precio
            = render :partial => "item", :collection =>@materials
      %br      
      = will_paginate @materials

app/views/price_lists/new.haml
.vertical_menu
  = render "admin/menu"
.contentright_s
  .box_bottom
    %h1 Nueva Lista de Precio
  = render "form"

app/views/price_lists/price_upload.js.erb
$("#impor_price_item").html("Precioas actualizados #{@result[:found]}");

app/views/price_lists/show.haml
%p
  %b
    Name:
  = h @price_list.name
= link_to image_tag('edit.png'), edit_price_list_path(@price_list)