config/routes.rb
ComunidadBox::Application.routes.draw do

  match 'auth/:provider/callback' => 'authentications#create'
  match "admin" => "admin#show"
  match "conf" => "conf#show"
  match "vgneumaticos"=>"guests#new"

  constraints CanAccessResque do
    mount Resque::Server, at: '/resque'
  end

  scope '(:locale)' do
    devise_for :users,:controllers => { :registrations => "users/registrations",:sessions =>'users/sessions',:confirmations =>"users/confirmations" }
    match "/help" => "help#index"

    resources :company_attributes
    resources :item_service_requests
    resources :service_requests
    resources :guests
    resources :authentications
    resources :service_filters
    resources :states
    resources :countries
    resources :brands
    resources :models do
      collection do
        post :import
      end
    end

    resources :notes
    resources :item_services
    resources :car_filters
    resources :ranks
    resources :tasks
    resources :payment_methods
    resources :service_type_templates
    resources :contacts
    resources :material_requests
    resources :advertising
    resources :statuses

    resources :messages do
      member do
        get :email
        post :read
      end

      collection do
        get :users
      end
    end

    resources :home do
      collection do
        post :set_company
      end
    end

    resources :messages do
      member do
        post :respond
      end
    end

    resources :events do
      resources :notes
      resources :alarms

      member do
        get :search_notes
      end
    end

    resources :budgets do
      resources :notes
      collection do
        get :export
      end
      member do
        get :print
        get :email
        get :email_s
        put :undelete
      end
    end

    resources :employees do
      collection do
        post :search
      end

      member do
        get :activate
      end

    end

    resources :workorders do
      collection do
        get :filter
        post :task_list
        get :autopart
        get :export
      end
      member do
        get :notify
        get :print
        get :price_offer
        post :save_price_offer
        get :price_offers
        put :confirm_price_offer
        put :undelete
      end
    end

   resources :companies do
      collection do
        get :service_types
        get :all
        get :admin
        post :search
        post :search_distance
        post :add_service_type
        post :remove_service_type
      end

      member do
        get :activate
      end
    end

    resources :vehicles do
      resources :alarms
      resources :notes

      collection do
        get :find_models
        get :find_brands
        post :find_company_models_by_brand
        post :search
        post :search_companies
        get :my
      end

      member do
        put :km
        get :services_done
        get :future_events
        get :report_graph
        get :notes
        get :alarms
        get :messages
      end
    end

    resources :users do
      resources :messages

      collection do
        get :generate_email
        get :validate_email
        get :validate_domain
        get :new_employee
        get :list_service_offer
        get :companies
        get :future_events
        post :find_models
        get :mail_confirmation
        get :reset_password
        get :unlock
      end

    end

    resources :alarms do
      collection do
        get :list_alarm_now
      end
      member do
        get :send_alarm
      end
    end

    resources :clients do
      collection do
        get :search
        get :index_all
        get :export
        get :import
        put :upload
      end
    end

    resources :services do
      collection do
        post :add_material
        post :add_service
      end
    end

    resources :control_panels do
      collection do
        post :filter_alarms
        get :filter_alarms
        post :find_models
        post :save_filter
      end
    end

    resources :service_offers do
      collection do
        post :send_notification
        post :new_s
        get :notify_email
        get :notify
      end
      member do
        get :show_ad
      end

    end

    resources :vehicle_service_offers do
      member do
        get :confirm
        get :reject
      end
      collection do
        get :confirmed
      end
    end

    resources :service_types do
      resources :materials do
        member do
          delete :remove
        end
      end

      member do
        get :task_list
        put :add_task
        delete :remove_task
        post :add_material
        post :protect
        post :unprotect
        get :search_material
      end

      collection do
        get :search_sub_category
        put :destroy_material
      end
    end

    resources :materials do

      resources :service_types do
        member do
          delete :remove
        end
      end
      collection do
        get :details
        get :export
        post :import
      end
    end

    resources :price_lists do
      member do
        get :activate
        get :items
        get :copy
        put :update_item_price
        put :price_upload
        get :export
      end

      collection do
        get :import_price
      end
    end

    resources :material_requests do
      collection do
        post :search
      end
      member do
        get :approved
        get :disapproved
      end
    end

    resources :exports do
      member do
        get :download
        get :run
      end
    end

    resources :company_material_codes do
      collection do
        get :export
        post :import
      end
    end

    root :to => "home#index"

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ApplicationHelper
  layout "application"
  skip_before_filter :authenticate_user!,:only =>:index
  
  def index
    if current_user
      @events = current_user.future_events(:per_page=>12)
    end

    if current_user && current_user.disable
      flash[:notice] = t(".access")
      redirect_to destroy_user_session_path
    end
  end

  def set_company   
    logger.debug "### Companies IDS #{params[:company_ids]} ALL Comp #{params[:all_company]}"
    id=params[:company_ids]

    if id.nil?
      id = [current_user.company.id]
    end

    unless (params[:all_company])
      ids = params[:all_company] || []
      if (current_user.get_companies_ids.find_all{|e| ids.include?(e)} == ids)
        set_company_in_cookie id
      end
    else
        set_company_in_cookie ["-1"]
    end

    redirect_to :back
  end
end

app/views/home/_advertisements.haml
- ads = ServiceOffer.today_advertisements
- unless ads.empty?
  .box_bottom
  .advertisements
    - ads.each do |service_offer|
      .advertisement
        .company_name
          = link_to service_offer.company.name,service_offer.company,:target =>"_blank"
        .ad_name
          = link_to service_offer.title,show_ad_service_offer_path(service_offer),:target =>"_blank",:title => t("service_offer")
        .price_info
          %span{:title =>t("price")}
            = number_to_currency(service_offer.price)
          %span{:title =>t("discount")}
            = number_to_percentage(service_offer.percent, :precision =>2)            
          %span.final_price{:title =>t("final_price")}
            = number_to_currency(service_offer.final_price)

app/views/home/_companies.haml
-@companies = Company.all(:order =>"created_at desc")
%h1 Últimos Prestadores de Servicios
%p
  %ul.list
    - @companies.each do |c|
      %li
        = c.name
        - if c.address
          =", #{c.address.state.name}"

= link_to "Prestadores", all_companies_path,:method =>:get,:class=>"button"

app/views/home/_home_ps.haml
%p
  Muchas gracias por usar Comunidad Box, Ud. podrá realizar una correcta administración de sus clientes,
  futuros servicios a realizar y mejorará la forma de comunicarse con ellos

app/views/home/_home_u.haml
%p
  Muchas gracias por usar Comunidad Box. Uds podra llevar un registro de los servicios realizado a sus automóviles y seleccionar el mejor prestado de servicios

app/views/home/_last_notice.haml
%h1 Últimas Noticias

app/views/home/_menu.haml
#menu_options.box_bottom
  %ul
    %li
      #vehicles_link.menu
        = image_tag "cars.png"
        - if company_id
          = link_to t(".clients"), clients_path
        - else
          = link_to t(".my_vehicles"), my_vehicles_path
    - if company_id
      %li
        #control_panel_link.menu
          = image_tag "control-panel.png"
          = link_to t(".control_panel"),control_panels_path
    %li
      #service_done_link.menu
        = image_tag "service.png"
        = link_to t(".services_made"),workorders_path
    %li
      #service_done_link.menu
        = image_tag "service.png"
        = link_to t(current_user.is_vehicle_owner? ? ".services_requests" : ".services_clients_request"), service_requests_path
    %li
      #control_panel_link.menu
        = image_tag "budget.png"
        = link_to t(".budgets"),budgets_path
    %li
      #service_offer.link.menu
        = image_tag "service_offer.png"
        - if company_id
          = link_to t(".service_offers") , service_offers_path
        - else
          = link_to t(".service_offers") , vehicle_service_offers_path

    = render "/home/new_menu"
    - unless current_user.close_system
      %li
        #service_center_link.menu
          = image_tag "find.png"
          = link_to t(".service_providers"), all_companies_path
#menu_actions
  #vehicles_menu.menu_data.hide.box_bottom
    =render :partial=>"vehicles/search_vehicle",:locals =>{:vehicles=>[],:table_id =>:sort_table}
  #clients_menu.menu_data.hide.box_bottom
    = render "clients/search_clients"

app/views/home/_my_events.haml
%h1 Nuevos Mensajes
%ul
  - @events.each do |e|
    %li
      ="#{e.service_type.name} #{e.dueDate}"
%p
#sendprestadores
  = button_to "Ver" , control_panels_path,:method =>:get,:class=>"button"

app/views/home/_new_menu.haml
%li
  #alarms_link.menu
    = image_tag "alarm.png",:class=> :left
    = link_to t(".alarms"),alarms_path,:class=> :left
    #today_alarm
      = alarm_today_nro
%li
  #messages_link.menu        
    = image_tag "message.png",:class=> :left
    = link_to t(".messages"), users_messages_path,:class => :left
    #unread_message_nro
      = unread_message_nro
%li
  #note.link.link.menu
    = image_tag "notes.png"
    = link_to  t(".notes"),notes_path

app/views/home/_new_msgs.haml
.box_bottom
.box_bottom
  .video.center
    %iframe{:allowfullscreen => "", :frameborder => "0", :height => "400", :mozallowfullscreen => "", :src => "http://player.vimeo.com/video/67908748", :webkitallowfullscreen => "", :width => "650"}
  %p    
    %a{:href => "http://vimeo.com/comunidadbox"} Tutoriales - ComunidadBox 

app/views/home/_nu_menu.haml
#menu_options.box_bottom
  %li
    #register_link.menu
      = image_tag "sign-up.png"
      = link_to t(".register"),new_user_registration_path
    .ajax_loader.right
  %li
    #service_center_link.menu
      = image_tag "find.png"
      = link_to t(".service_providers"), all_companies_path
  %li
    #service_center_link.menu
      = image_tag "help.png"
      = link_to t(".help"), help_path

#menu_actions
  #service_center_menu.menu_data.hide      
    =render :partial=>"companies/search"

app/views/home/_sliders.haml
#s3slider
  %ul#s3sliderContent
    %li.s3sliderImage
      = image_tag "home/pantalla-1.png"      
      %span
        %strong Servicios Realizados
        %br Consulte los servicios realizados por fecha, estado, tipo y dominio
    %li.s3sliderImage
      = image_tag "home/pantalla-2.png"
      %span 
        %strong Reportes Gráficos
        %br Visualize en forma gráfica servicios realizados
    %li.s3sliderImage
      = image_tag "home/pantalla-3.png"
      %span 
        %strong Listado de Clientes
        %br Localize automóviles, y clientes de forma rápida
    %li.s3sliderImage
      = image_tag "home/pantalla-4.png"
      %span 
        %strong Prestadores de Servicio
        %br Localize Prestadores de Servicios en Google Map
    %li.s3sliderImage
      = image_tag "home/pantalla-5.png"
      %span 
        %strong Panel de Control
        %br Visualize en forma gráfica vencimientos de servicios a realizar
    %li.s3sliderImage
      = image_tag "home/pantalla-6.png"
      %span
        %strong Servicios a Realizar
        %br Visualize eventos a realizar, y cree ofertas de servicio 
    %li.s3sliderImage
      = image_tag "home/pantalla-7.png"
      %span
        %strong Servicios Realizados
        %br Visualize los servicios realizados a un automóvil
    %li.s3sliderImage
      = image_tag "home/pantalla-8.png"
      %span
        %strong Reporte Grafico
        %br Visualize en forma gráfica servicios realizados
    .clear.s3sliderImage

app/views/home/_welcome_msg.haml
.shadown2.title
  #cont1
    #comunidadbox
      %h1=t(".welcome")  
      %span.hide=t(".message1")
      %h2
        %span#cont1=t(".message2")
        %br
      - if user_signed_in?
        - if company_id && get_service_types.empty?
          = link_to t(".message3"), service_types_companies_path

app/views/home/_what_is_combo.haml
.doc_row.box_bottom
  .video_home.center
    %iframe{:allowfullscreen => "", :frameborder => "0", :height => "481", :mozallowfullscreen => "", :src => "http://player.vimeo.com/video/67908748", :webkitallowfullscreen => "", :width => "700"}
  %p
    = link_to t(".tutorials") , "http://vimeo.com/comunidadbox"

app/views/home/welcome.haml
= render "home/welcome_msg"
= render "home/new_msgs"